### ISSUE TITLE
[PE-D][Tester C] No input feedback

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-1/tp#46]
![image.png](https://raw.githubusercontent.com/onx001/ped/main/files/6b3632d5-472a-46be-8f42-e13d41b1b7d2.png)
There is no way of telling if a command entered is legitimate, nor for listing the previous submitted requests.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: onx001/ped#3

**Comment by J-Y-Yan** [comment]
duplicated feedback. Plz don't give meaningless comments and waste time
